# -*- mode: ruby -*-
# vi: set ft=ruby :

#--------------------------------------------------------------------------------------------
# Autor.: Jonathan Costa
# Data..: 23/06/2022
# Descrição.: 
#
# OBS.: Libvirt -->   Para a utilização do Vagrant no Fedora 36, estou utilizando o 
#                     provider "libvirt" e seu pacote vagrant-libvirt, por conta 
#                     disso estou seguindo a documentação desse provider disponivel 
#                     na seguinte página do GitHub:
#                     - https://github.com/vagrant-libvirt/vagrant-libvirt
#
#--------------------------------------------------------------------------------------------

Vagrant.configure("2") do |config|
  config.vm.box = "generic/oracle8"
 
  # Por falta de criatividade e excesso de bom gosto (rsrs)
  # o nome para máquina de labs será shinobi (Ref.: Naruto)
  config.vm.define :shinobi do |shi|
  end

  # Configuração dos Recursos Fisicos da Máquina Virtual
  config.vm.provider "libvirt" do |lv|
    lv.memory = 8192
    lv.cpus = 4
  end

end
